const CONFIG={locationQuery:'نادي الزهراء الرياضي القاهرة مصر',rsvpUrl:'',photosUrl:''};
const page1=document.getElementById('page1'),page2=document.getElementById('page2'),openBtn=document.getElementById('openInvitation'),transition=document.getElementById('transition'),canvas=document.getElementById('matrixCanvas'),music=document.getElementById('bgMusic'),clickSound=document.getElementById('clickSound'),toast=document.getElementById('toast'),modal=document.getElementById('rsvpModal');
let musicStarted=false,transitioning=false,animationId,columns=[];
function playClick(){try{clickSound.currentTime=0;clickSound.play().catch(()=>{})}catch(e){}}
function startMusic(){if(musicStarted)return;musicStarted=true;music.volume=.65;music.play().catch(()=>{musicStarted=false})}
function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2600)}
function setupMatrix(){const dpr=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const count=Math.ceil(w/24);columns=Array.from({length:count},(_,i)=>({x:i*24+Math.random()*12,y:-Math.random()*h,len:8+Math.floor(Math.random()*18),speed:5+Math.random()*8,red:Math.random()<.13,width:Math.random()<.22?2:1}));return ctx}
function drawMatrix(ctx){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);columns.forEach(c=>{c.y+=c.speed;if(c.y-c.len*20>h)c.y=-Math.random()*500;const grad=ctx.createLinearGradient(c.x,c.y-c.len*20,c.x,c.y);const rgb=c.red?'255,55,70':'225,228,230';grad.addColorStop(0,`rgba(${rgb},0)`);grad.addColorStop(.65,`rgba(${rgb},.18)`);grad.addColorStop(1,`rgba(${rgb},.9)`);ctx.strokeStyle=grad;ctx.lineWidth=c.width;ctx.beginPath();ctx.moveTo(c.x,c.y-c.len*20);ctx.lineTo(c.x,c.y);ctx.stroke();ctx.shadowBlur=c.red?14:10;ctx.shadowColor=c.red?'rgba(255,45,55,.75)':'rgba(235,238,240,.65)';ctx.fillStyle=c.red?'rgba(255,75,85,.9)':'rgba(245,247,248,.9)';ctx.beginPath();ctx.arc(c.x,c.y,1.4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});animationId=requestAnimationFrame(()=>drawMatrix(ctx))}
function startTransition(){if(transitioning)return;transitioning=true;playClick();startMusic();transition.classList.add('show');const ctx=setupMatrix();cancelAnimationFrame(animationId);drawMatrix(ctx);setTimeout(()=>{page1.classList.remove('active');page2.classList.add('active');page2.setAttribute('aria-hidden','false');page1.setAttribute('aria-hidden','true')},720);setTimeout(()=>{transition.classList.remove('show');cancelAnimationFrame(animationId);transitioning=false},1450)}
openBtn.addEventListener('click',startTransition);
addEventListener('resize',()=>{if(transition.classList.contains('show')){const ctx=setupMatrix();cancelAnimationFrame(animationId);drawMatrix(ctx)}});
document.querySelectorAll('.action').forEach(btn=>btn.addEventListener('click',()=>{playClick();startMusic();const a=btn.dataset.action;if(a==='location')window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(CONFIG.locationQuery),'_blank','noopener');if(a==='share'){const data={title:'محمد خليفة & سارة عيد',text:'دعوتكم لحضور حفلة خطوبتنا يوم الإثنين ٢٢ يونيو ٢٠٢٦ الساعة ٦ مساءً ❤️',url:location.href};if(navigator.share)navigator.share(data).catch(()=>{});else navigator.clipboard?.writeText(location.href).then(()=>showToast('تم نسخ رابط الدعوة ❤️')).catch(()=>showToast('انسخي رابط الدعوة من شريط المتصفح'))}if(a==='photos'){if(CONFIG.photosUrl)window.open(CONFIG.photosUrl,'_blank','noopener');else showToast('صور الحفلة هتكون متاحة قريبًا ❤️')}if(a==='rsvp'){if(CONFIG.rsvpUrl)window.open(CONFIG.rsvpUrl,'_blank','noopener');else modal.classList.add('open')}}));
document.getElementById('closeModal').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.querySelectorAll('[data-rsvp]').forEach(btn=>btn.addEventListener('click',()=>{const ans=btn.dataset.rsvp==='yes'?'سأحضر ❤️':'أعتذر عن الحضور';navigator.clipboard?.writeText(`محمد خليفة & سارة عيد — ${ans}`).catch(()=>{});modal.classList.remove('open');showToast('تم اختيار الرد: '+ans)}));document.getElementById('musicToggle').addEventListener('click',()=>{if(music.paused){music.play().catch(()=>{});showToast('تم تشغيل الموسيقى 🎵')}else{music.pause();showToast('تم إيقاف الموسيقى')}});
